# Upsert (update or insert) a user based on their auth.uid
mutation UpsertUser($phoneNumber: String, $email: String) @auth(level: USER) {
  user_upsert(
    data: { uid_expr: "auth.uid", phoneNumber: $phoneNumber, email: $email }
  )
}
