# Upsert (update or insert) a user based on their auth.uid
mutation UpsertUser($phoneNumber: String, $email: String) @auth(level: USER) {
  user_upsert(
    data: { uid_expr: "auth.uid", phoneNumber: $phoneNumber, email: $email }
  )
}

mutation upsertProduct(
  $name: String!
  $description: String
  $price: Float!
  $inventory: Int!
) @auth(level: USER) {
  product_upsert(
    data: {
      id_expr: "uuidV4()"
      userId_expr: "auth.uid"
      name: $name
      description: $description
      price: $price
      inventory: $inventory
    }
  )
}
