#!/bin/sh

# First provide access to the nvm command.
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 

# Use the nvm ls command to detect the version being used.
NODE_VERSION=$(nvm ls --no-colors | grep '^node' | grep -oE 'v[0-9]+.[0-9]+.[0-9]+') 
NODE_BIN_PATH="$NVM_DIR/versions/node/$NODE_VERSION/bin"

# Export the current version in your path for husky to find.
export PATH="$NODE_BIN_PATH:$PATH"

npx lint-staged
