type User
  @table(name: "Users", singular: "user", plural: "users", key: ["uid"]) {
  uid: String! @default(expr: "auth.uid")
  phoneNumber: String @unique
  email: String @unique

  createdAt: Timestamp! @col(name: "created_at") @default(expr: "request.time")
}

type Product
  @table(
    name: "Products"
    singular: "product"
    plural: "products"
    key: ["id"]
  ) {
  id: String! @default(expr: "uuidV4()")
  userId: String! @col(name: "user_id")
  name: String!
  description: String
  price: Float!
  inventory: Int!
}
